"""Type stubs for ferrosync."""

from __future__ import annotations

import enum
from typing import Any, Callable

__version__: str

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class DeleteMode(enum.IntEnum):
    # Note: access the "None" variant via getattr(DeleteMode, "None")
    # since `None` is a Python keyword.
    Before = 1
    During = 2
    After = 3
    Excluded = 4

class Verbosity(enum.IntEnum):
    Quiet = 0
    Normal = 1
    Verbose = 2
    VeryVerbose = 3
    Debug = 4

class ChecksumType(enum.IntEnum):
    # Note: access the "None" variant via getattr(ChecksumType, "None")
    # since `None` is a Python keyword.
    Md4 = 1
    Md5 = 2

# ---------------------------------------------------------------------------
# Classes
# ---------------------------------------------------------------------------

class TransferOptions:
    def __init__(
        self,
        *,
        source: list[str] = ...,
        dest: str | None = ...,
        archive: bool = ...,
        recursive: bool = ...,
        preserve_links: bool = ...,
        preserve_perms: bool = ...,
        preserve_times: bool = ...,
        preserve_group: bool = ...,
        preserve_owner: bool = ...,
        preserve_devices: bool = ...,
        preserve_specials: bool = ...,
        checksum_mode: bool = ...,
        whole_file: bool = ...,
        update: bool = ...,
        inplace: bool = ...,
        delete: DeleteMode = ...,
        compress: bool = ...,
        compress_level: int = ...,
        verbosity: Verbosity = ...,
        progress: bool = ...,
        stats: bool = ...,
        dry_run: bool = ...,
        itemize_changes: bool = ...,
        exclude: list[str] = ...,
        include: list[str] = ...,
        filter: list[str] = ...,
        bwlimit: int | None = ...,
        max_size: int | None = ...,
        min_size: int | None = ...,
        timeout: int | None = ...,
        link_dest: list[str] = ...,
        copy_dest: list[str] = ...,
        compare_dest: list[str] = ...,
        backup: bool = ...,
        backup_dir: str | None = ...,
        suffix: str = ...,
        partial_dir: str | None = ...,
        append: bool = ...,
        files_from: str | None = ...,
        one_file_system: bool = ...,
        numeric_ids: bool = ...,
        sparse: bool = ...,
    ) -> None: ...

    @property
    def recursive(self) -> bool: ...
    @property
    def preserve_links(self) -> bool: ...
    @property
    def preserve_perms(self) -> bool: ...
    @property
    def preserve_times(self) -> bool: ...
    @property
    def preserve_group(self) -> bool: ...
    @property
    def preserve_owner(self) -> bool: ...
    @property
    def preserve_devices(self) -> bool: ...
    @property
    def preserve_specials(self) -> bool: ...
    @property
    def checksum_mode(self) -> bool: ...
    @property
    def whole_file(self) -> bool: ...
    @property
    def update(self) -> bool: ...
    @property
    def inplace(self) -> bool: ...
    @property
    def delete(self) -> DeleteMode: ...
    @property
    def compress(self) -> bool: ...
    @property
    def compress_level(self) -> int: ...
    @property
    def verbosity(self) -> Verbosity: ...
    @property
    def progress(self) -> bool: ...
    @property
    def stats(self) -> bool: ...
    @property
    def dry_run(self) -> bool: ...
    @property
    def itemize_changes(self) -> bool: ...
    @property
    def exclude(self) -> list[str]: ...
    @property
    def include(self) -> list[str]: ...
    @property
    def filter(self) -> list[str]: ...
    @property
    def source(self) -> list[str]: ...
    @property
    def dest(self) -> str | None: ...
    @property
    def bwlimit(self) -> int | None: ...
    @property
    def max_size(self) -> int | None: ...
    @property
    def min_size(self) -> int | None: ...
    @property
    def timeout(self) -> int | None: ...
    @property
    def link_dest(self) -> list[str]: ...
    @property
    def copy_dest(self) -> list[str]: ...
    @property
    def compare_dest(self) -> list[str]: ...
    @property
    def backup(self) -> bool: ...
    @property
    def backup_dir(self) -> str | None: ...
    @property
    def suffix(self) -> str: ...
    @property
    def partial_dir(self) -> str | None: ...
    @property
    def append(self) -> bool: ...
    @property
    def files_from(self) -> str | None: ...
    @property
    def one_file_system(self) -> bool: ...
    @property
    def numeric_ids(self) -> bool: ...
    @property
    def sparse(self) -> bool: ...

    def is_archive(self) -> bool: ...

class SyncResult:
    @property
    def files_transferred(self) -> int: ...
    @property
    def total_files(self) -> int: ...
    @property
    def bytes_sent(self) -> int: ...
    @property
    def bytes_received(self) -> int: ...
    @property
    def total_size(self) -> int: ...
    @property
    def matched_data(self) -> int: ...
    @property
    def literal_data(self) -> int: ...
    @property
    def files_skipped(self) -> int: ...
    @property
    def files_deleted(self) -> int: ...
    @property
    def symlinks(self) -> int: ...
    @property
    def directories_created(self) -> int: ...
    @property
    def elapsed_secs(self) -> float: ...
    @property
    def transfer_rate(self) -> float: ...
    @property
    def speedup(self) -> float: ...

class FileEntry:
    @property
    def name(self) -> str: ...
    @property
    def name_bytes(self) -> bytes: ...
    @property
    def size(self) -> int: ...
    @property
    def mtime(self) -> int: ...
    @property
    def mtime_nsec(self) -> int: ...
    @property
    def mode(self) -> int: ...
    @property
    def uid(self) -> int: ...
    @property
    def gid(self) -> int: ...
    @property
    def is_file(self) -> bool: ...
    @property
    def is_dir(self) -> bool: ...
    @property
    def is_symlink(self) -> bool: ...
    @property
    def is_device(self) -> bool: ...
    @property
    def link_target(self) -> str | None: ...

# ---------------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------------

def sync_files(
    options: TransferOptions,
    *,
    progress_callback: Callable[[dict[str, Any]], None] | None = ...,
    checksum_seed: int = ...,
    checksum_type: ChecksumType = ...,
) -> SyncResult: ...

async def async_sync_files(
    options: TransferOptions,
    *,
    progress_callback: Callable[[dict[str, Any]], None] | None = ...,
    checksum_seed: int = ...,
    checksum_type: ChecksumType = ...,
) -> SyncResult: ...

def logging_progress_callback(event: dict[str, Any]) -> None: ...

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class FerrosyncError(Exception): ...
class ProtocolError(FerrosyncError): ...
class TransportError(FerrosyncError): ...
class FilesystemError(FerrosyncError): ...
class FilterError(FerrosyncError): ...
class ChecksumMismatchError(ProtocolError): ...
